//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonterbontLODConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KonterbontLODConnector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #targetengine &quot;session&quot;
        ///
        ////*
        /// * 
        /// * json2.jsx
        /// * 
        /// * 
        /// */
        ///
        ///if (typeof JSON !== &apos;object&apos;) {
        ///    JSON = {};
        ///}
        ///
        ///(function () {
        ///    &apos;use strict&apos;;
        ///
        ///    function f(n) {
        ///        return n &lt; 10 ? &apos;0&apos; + n : n;
        ///    }
        ///
        ///    if (typeof Date.prototype.toJSON !== &apos;function&apos;) {
        ///
        ///        Date.prototype.toJSON = function () {
        ///
        ///            return isFinite(this.valueOf())
        ///                ? this.getUTCFullYear() + &apos;-&apos; +
        ///                f(this.getUTCMonth() + 1) + &apos;-&apos; +
        ///                f(this.getUTCDate( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _01_prepare_doc {
            get {
                return ResourceManager.GetString("_01_prepare_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #target &quot;indesign&quot;
        ///#targetengine &quot;com.twixlmedia.publisher.idserver&quot;
        ///#include &quot;zz_twixlForServer.jsx&quot;;
        ///
        ///var magazineFolderPath = &quot;K:\\Magazines\\&quot;;
        ///
        ///var firstArg = arguments[0];
        ///
        ///alert(&quot;Arguments: &quot; + firstArg);.
        /// </summary>
        public static string _02_export_article {
            get {
                return ResourceManager.GetString("_02_export_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #target &quot;indesign&quot;
        ///#targetengine &quot;com.twixlmedia.publisher.idserver&quot;
        ///#include &quot;zz_twixlForServer.jsx&quot;;
        ///
        ///var magazineFolderPath = &quot;K:\\Magazines\\&quot;;
        ///
        ///var myBookContents = TMUtilities.collectionToArray(app.activeBook.bookContents);
        ///var myBookContentsCount = myBookContents.length;
        ///for (var ii = 0; ii &lt; myBookContentsCount; ii++) {
        ///    var myFile = myBookContents[ii];
        ///    var exportFileNamePath = myFile.fullName.name.split(&apos;.&apos;)[0];
        ///    $.writeln(exportFileNamePath);
        ///    if (ii == 0) {
        ///        //Cov [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _02_Export_Articles_From_Book {
            get {
                return ResourceManager.GetString("_02_Export_Articles_From_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #target &quot;indesign&quot;
        ///#targetengine &quot;com.twixlmedia.publisher.idserver&quot;
        ///#include &quot;zz_twixlForServer.jsx&quot;;
        ///
        ///var magazineFolderPath = &quot;K:\\Magazines\\&quot;;
        ///var destinationPath = magazineFolderPath + app.activeBook.name.substr(0, 7) + &quot;\\export\\&quot; + app.activeBook.name.substr(0, 7) + &quot;.publication&quot;;
        ///var myFile = app.activeBook.fullName.fsName;
        ///
        ///TwixlPublisherPluginAPI.exportPublication(app.activeBook, destinationPath);
        ///
        ///.
        /// </summary>
        public static string _02_Export_Book {
            get {
                return ResourceManager.GetString("_02_Export_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit_16x {
            get {
                object obj = ResourceManager.GetObject("Exit_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FreightSansCmpPro_BookItalic {
            get {
                object obj = ResourceManager.GetObject("FreightSansCmpPro_BookItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FreightSansCmpPro_Med {
            get {
                object obj = ResourceManager.GetObject("FreightSansCmpPro_Med", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FreightSansCmpPro_Semi {
            get {
                object obj = ResourceManager.GetObject("FreightSansCmpPro_Semi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NewFile_16x {
            get {
                object obj = ResourceManager.GetObject("NewFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OpenFile_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OpenFileFromProject_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFileFromProject_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0,user-scalable=no&quot;&gt;
        ///		&lt;title&gt;popup&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;popupstyle.css&quot;/&gt;
        ///		&lt;style&gt;
        ///			.highlight, .marker-color { color: rgb(leColorCSScolor) !important; color:yellow; } 
        ///			p.Tab_Wuert {  color: rgb(leColorCSScolor) !important; }
        ///			div.divTableBody { height:100%; width:100%; background-color:rgb(leC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string popup {
            get {
                return ResourceManager.GetString("popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @font-face {
        ///  font-family: &apos;FreightSansCmpPro Med&apos;;
        ///  src: url(&apos;FreightSansCmpPro-Med.ttf&apos;)  format(&apos;truetype&apos;);
        ///}
        ///@font-face {
        ///  font-family: &apos;FreightSansCmpPro Semi&apos;;
        ///  src: url(&apos;FreightSansCmpPro-Semi.ttf&apos;)  format(&apos;truetype&apos;);
        ///}
        ///@font-face {
        ///  font-family: &apos;FreightSansCmpPro Book Italic&apos;;
        ///  src: url(&apos;FreightSansCmpPro-BookItalic.ttf&apos;)  format(&apos;truetype&apos;);
        ///}
        ///@media screen and (orientation: portrait) {
        ///	/* phone-specific style */
        ///	.flex-innercontainer { flex-direction: column;margin:5px 5px [rest of string was truncated]&quot;;.
        /// </summary>
        public static string popupstyle {
            get {
                return ResourceManager.GetString("popupstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_16xMD {
            get {
                object obj = ResourceManager.GetObject("save_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SaveStatusBar8_16x {
            get {
                object obj = ResourceManager.GetObject("SaveStatusBar8_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectFileGroup_16x {
            get {
                object obj = ResourceManager.GetObject("SelectFileGroup_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * ------------------------------------------------------------------------
        /// * Twixl media Confidential
        /// * ------------------------------------------------------------------------
        /// *
        /// * (c) 2010-2016 Twixl media, http://twixlmedia.com
        /// *
        /// * NOTICE: All information contained herein is, and remains the property of
        /// * Twixl media and its suppliers, if any. The intellectual and technical
        /// * concepts contained herein are proprietary to Twixl media and its
        /// * suppliers and may be covered by U.S. and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string zz_twixlForServer {
            get {
                return ResourceManager.GetString("zz_twixlForServer", resourceCulture);
            }
        }
    }
}
