//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonterbontLODConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KonterbontLODConnector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;lb&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0,user-scalable=no&quot;&gt;
        ///    &lt;title&gt;popup&lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css?&quot;&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;jquery.js&quot;&gt;&lt;/script&gt;
        ///	&lt;script id=&quot;scriptpath&quot; type=&quot;text/javascript&quot; src=&quot;__JSON_PATH__&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	
        ///&lt;div class=&quot;flex-container&quot;&gt;
        ///        &lt;div class=&quot;flex-child&quot;&gt;
        ///            &lt;div class=&quot;flex-innercontainer&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bases {
            get {
                return ResourceManager.GetString("bases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #targetengine &quot;session&quot;
        ///
        ////*
        /// * 
        /// * json2.jsx
        /// * 
        /// * 
        /// */
        ///
        ///if (typeof JSON !== &apos;object&apos;) {
        ///    JSON = {};
        ///}
        ///
        ///(function () {
        ///    &apos;use strict&apos;;
        ///
        ///    function f(n) {
        ///        return n &lt; 10 ? &apos;0&apos; + n : n;
        ///    }
        ///
        ///    if (typeof Date.prototype.toJSON !== &apos;function&apos;) {
        ///
        ///        Date.prototype.toJSON = function () {
        ///
        ///            return isFinite(this.valueOf())
        ///                ? this.getUTCFullYear() + &apos;-&apos; +
        ///                f(this.getUTCMonth() + 1) + &apos;-&apos; +
        ///                f(this.getUTCDate( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string create_popups_script {
            get {
                return ResourceManager.GetString("create_popups_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit_16x {
            get {
                object obj = ResourceManager.GetObject("Exit_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FreightSansCmpPro_BookItalic {
            get {
                object obj = ResourceManager.GetObject("FreightSansCmpPro_BookItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FreightSansCmpPro_Med {
            get {
                object obj = ResourceManager.GetObject("FreightSansCmpPro_Med", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FreightSansCmpPro_Semi {
            get {
                object obj = ResourceManager.GetObject("FreightSansCmpPro_Semi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v3.4.1
        /// * https://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * https://sizzlejs.com/
        /// *
        /// * Copyright JS Foundation and other contributors
        /// * Released under the MIT license
        /// * https://jquery.org/license
        /// *
        /// * Date: 2019-05-01T21:04Z
        /// */
        ///( function( global, factory ) {
        ///
        ///	&quot;use strict&quot;;
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///
        ///		// For CommonJS and CommonJS-like environments where a proper `window`
        ///		// is present, execute the f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let KBHandler = {
        ///	_selword:null,
        ///	_selwordid:null,
        ///	
        ///	init:function(){
        ///		_selwordid = 0;
        ///	},
        ///	setWord:function(selectedWord)
        ///	{
        ///		_selword = selectedWord;
        ///	},
        ///	getWord:function()
        ///	{
        ///		let url = new URL(window.location.href);
        ///		this.setWord(url.searchParams.get(&quot;word&quot;));
        ///		if (_selword!=null)
        ///		{
        ///			//_selwordid = 0;
        ///			for (var i = 0; i &lt; theObject.wordlist.length; i++)
        ///			{
        ///				if (theObject.wordlist[i].Occurence == _selword) { _selwordid=i; }
        ///				if (_selwordid != null) 
        ///				{ 
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string kbhandler {
            get {
                return ResourceManager.GetString("kbhandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NewFile_16x {
            get {
                object obj = ResourceManager.GetObject("NewFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OpenFile_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OpenFileFromProject_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFileFromProject_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_16xMD {
            get {
                object obj = ResourceManager.GetObject("save_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SaveStatusBar8_16x {
            get {
                object obj = ResourceManager.GetObject("SaveStatusBar8_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectFileGroup_16x {
            get {
                object obj = ResourceManager.GetObject("SelectFileGroup_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @font-face {
        ///  font-family: &apos;FreightSansCmpPro Med&apos;;
        ///  src: url(&apos;FreightSansCmpPro-Med.ttf&apos;)  format(&apos;truetype&apos;);
        ///}
        ///@font-face {
        ///  font-family: &apos;FreightSansCmpPro Semi&apos;;
        ///  src: url(&apos;FreightSansCmpPro-Semi.ttf&apos;)  format(&apos;truetype&apos;);
        ///}
        ///@font-face {
        ///  font-family: &apos;FreightSansCmpPro Book Italic&apos;;
        ///  src: url(&apos;FreightSansCmpPro-BookItalic.ttf&apos;)  format(&apos;truetype&apos;);
        ///}
        ///@media screen and (orientation: portrait) {
        ///	/* phone-specific style */
        ///	.flex-innercontainer { flex-direction: column;margin:5px 5px [rest of string was truncated]&quot;;.
        /// </summary>
        public static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
