// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KonterbontLODConnector;
//
//    var lodSearch = LodSearch.FromJson(jsonString);

namespace KonterbontLODConnector
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LodSearch
    {
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("results")]
        public List<Result> Results { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("word_lb")]
        public string WordLb { get; set; }

        [JsonProperty("scientific_name")]
        public string ScientificName { get; set; }

        [JsonProperty("pos")]
        public string Pos { get; set; }

        [JsonProperty("article_id")]
        public string ArticleId { get; set; }

        [JsonProperty("meanings")]
        public List<LodMeaning> Meanings { get; set; }
    }

    public partial class LodMeaning
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("translation")]
        public string Translation { get; set; }

        [JsonProperty("meaning")]
        public string MeaningMeaning { get; set; }

        [JsonProperty("number")]
        public long Number { get; set; }
    }

    public partial class LodSearch
    {
        public static LodSearch FromJson(string json) => JsonConvert.DeserializeObject<LodSearch>(json, KonterbontLODConnector.Converter.Settings);
    }
}
